apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |-
    input {
      tcp {
        port => 5000
      }
      http {
        port => 8080
      }
    }

    filter {
      # Add filters here
    }

    output {
      if [type] == "tcp" {
        elasticsearch {
          hosts => ["http://elasticsearch-0.elasticsearch:9200", "http://elasticsearch-1.elasticsearch:9200", "http://elasticsearch-2.elasticsearch:9200"]
          index => "mule-http-logs"
        }
      }


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  selector:
    matchLabels:
      app: logstash
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.13.4
          ports:
            - containerPort: 5000
              name: tcp
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline
      volumes:
        - name: pipeline
          configMap:
            name: logstash-config
            items:
              - key: logstash.conf
                path: logstash.conf
---

apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk
spec:
  selector:
    app: logstash
  ports:
    - name: tcp
      port: 5000
      targetPort: 5000
      nodePort: 31300
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31400
  type: NodePort
