apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      grok {
          match => { "message" => "%{SYSLOGLINE}" }
      }
      date {
        match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
      }
      geoip {
          source => "clientip"
        }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-0.elasticsearch:9200", "http://elasticsearch-1.elasticsearch:9200", "http://elasticsearch-2.elasticsearch:9200"]
        index => "ofm_dev"
      }
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: elk
data:
  pipeline.conf: |
    input {
      tcp {
        port => 5045
        codec => json
        
      }
      http {
        port => 9600
        codec => json
      }
    }
    filter {
      if [type] == "tcp" {
        date {
          match => [ "timeMillis", "UNIX_MS" ]
        }
      } else if [type] == "http" {
        grok {
          match => [ "message", "%{COMBINEDAPACHELOG}" ]
        }
        date {
          match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
        }
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-0.elasticsearch:9200", "http://elasticsearch-1.elasticsearch:9200", "http://elasticsearch-2.elasticsearch:9200"]
        index => "mule-http-logs"
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elk
spec:
  selector:
    matchLabels:
      app: logstash
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.9.0
          ports:
            - containerPort: 5044
              name: beats
            - containerPort: 5045
              name: tcp
            - containerPort: 9600
              name: http
          volumeMounts:
            - name: config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline/pipeline.conf
              subPath: pipeline.conf
      volumes:
        - name: config
          configMap:
            name: logstash-config
        - name: pipeline
          configMap:
            name: logstash-pipeline

---

apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk
spec:
  selector:
    app: logstash
  type: NodePort
  ports:
    - name: beats
      port: 5044
      targetPort: 5044
      nodePort: 31300
    - name: tcp
      port: 5045
      targetPort: 5045
      nodePort: 31200
    - name: http
      port: 9600
      targetPort: 9600
      nodePort: 31400
