apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
      tcp {
        port => 5045
        codec => json
      }
      http {
        port => 8080
        codec => json
      }
    }
    filter {
      if [type] == "beats" {
        grok {
          match => { "message" => "%{SYSLOGLINE}" }
        }
        date {
          match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
        }
        geoip {
          source => "clientip"
        }
      } else if [type] == "tcp" {
        date {
          match => [ "timeMillis", "UNIX_MS" ]
        }
      } else if [type] == "http" {
        date {
          match => [ "timeMillis", "UNIX_MS" ]
        }
      }
    }
    output {
      if [type] == "beats" {
        elasticsearch {
          hosts => ["http://elasticsearch-0.elasticsearch:9200", "http://elasticsearch-1.elasticsearch:9200", "http://elasticsearch-2.elasticsearch:9200"]
          index => "beats-logs"
        }
      } else if [type] == "tcp" {
        elasticsearch {
          hosts => ["http://elasticsearch-0.elasticsearch:9200", "http://elasticsearch-1.elasticsearch:9200", "http://elasticsearch-2.elasticsearch:9200"]
          index => "tcp-logs"
        }
      } else if [type] == "http" {
        elasticsearch {
          hosts => ["http://elasticsearch-0.elasticsearch:9200", "http://elasticsearch-1.elasticsearch:9200", "http://elasticsearch-2.elasticsearch:9200"]
          index => "http-logs"
        }
      }
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: elk
data:
  pipeline.conf: |
    output {
      if [type] == "tcp" {
        elasticsearch {
          hosts => ["http://elasticsearch-0.elasticsearch:9200", "http://elasticsearch-1.elasticsearch:9200", "http://elasticsearch-2.elasticsearch:9200"]
          index => "tcp-logs"
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elk
spec:
  selector:
    matchLabels:
      app: logstash
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.9.0
          ports:
            - containerPort: 5044
              name: beats
            - containerPort: 5045
              name: tcp
            - containerPort: 8080 
              name: http
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: logstash-pipeline
              mountPath: /usr/share/logstash/pipeline/pipeline.conf
              subPath: pipeline.conf
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
        - name: logstash-pipeline
          configMap:
            name: logstash-pipeline


---

apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk
spec:
  selector:
    app: logstash
  ports:
    - name: beats
      port: 5044
      targetPort: 5044
      nodePort: 31200
    - name: tcp
      port: 5045
      targetPort: 5045
      nodePort: 31300
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31400
  type: NodePort
