filebeat.inputs:
- type: container
  paths:
    - /var/log/pods/*/*.log
  processors:
    - add_kubernetes_metadata:
        host: ${NODE_NAME}
        matchers:
          - logs_path:
              logs_path: "/var/log/pods/"
  json.keys_under_root: true
  json.overwrite_keys: true
  tags: ["kubernetes"]

output.elasticsearch:
  hosts: ["http://elasticsearch-0.elasticsearch:9200", "http://elasticsearch-1.elasticsearch:9200", "http://elasticsearch-2.elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

