apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: elk
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.30.3
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
              readOnly: true
            - name: prometheus-storage
              mountPath: /prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-server-conf
        - name: prometheus-storage
          emptyDir: {}

apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: elk
spec:
  selector:
    app: prometheus-server
  ports:
    - name: http
      port: 80
      targetPort: 9090
  type: Nodeport
