name: sonar

on:
  pull_request:
    branches:
      - main

jobs:

  common:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: sonar
        run: |

          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856.zip -O /tmp/sonar-scanner.zip
          unzip /tmp/sonar-scanner.zip -d /tmp
          mv /tmp/sonar-scanner-* /tmp/sonar-scanner
          rm /tmp/sonar-scanner.zip
          export PATH="$PATH:/tmp/sonar-scanner/bin"

          sonar-scanner -X \
            -Dsonar.projectKey=santhosh \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://uspgh-neks-t4.amer.thermo.com:30653/ \
            -Dsonar.token=squ_d5b4c1c71b3e6c57c9dc4ad32e80205bef8f6332
